# OLX Ko'chmas mulk — Malumot Tozalash jaroyoni  
Kodni tepadan paga qarab yurg'azing. Oxirida sizda tayor `cleaned.csv` fileli modeling uchun tayor bo'ladi.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display, Markdown

In [2]:
df = pd.read_csv('/Users/javohireshonov/Desktop/Study/Projects/Tashkent apartment analysis/data/Praperad/olx_apartments.csv')
print(f'Loaded: {df.shape[0]:,} rows, {df.shape[1]} columns')

Loaded: 27,077 rows, 28 columns

In [3]:
df.isna().sum()

listing_id             0
seller_type            1
housing_type        8900
region                 1
district               1
rooms                  1
living_area_m2     18513
kitchen_area_m2    21182
total_area_m2          4
floor                  2
total_floors           1
building_type       6844
layout              9478
build_year         19542
ceiling_height     17821
bathroom            7633
furnished              3
renovation          4969
commission             1
amenities           9927
nearby              8958
negotiable             0
price                 60
currency               0
published_date         1
description            1
date_scraped           0
url                    0
dtype: int64

In [4]:
df.head()

,listing_id,seller_type,housing_type,region,district,rooms,living_area_m2,kitchen_area_m2,total_area_m2,floor,...,commission,amenities,nearby,negotiable,price,currency,published_date,description,date_scraped,url
0,4jYx9,private,resale,Tashkent Region,Chilanzar District,1.0,20.0,6.0,29.0,1.0,...,0.0,"Internet, Refrigerator, TV, Air Conditioning, ...","Hospital, Clinic, Playground, Kindergarten, Bu...",1,60000.0,USD,01/05/2026,Описание Уй локацияси зур жойда жойлашган. Мир...,2026-05-02,https://www.olx.uz/d/obyavlenie/1-hona-metro-o...
1,4myoT,private,NaN,Tashkent Region,Yunusabad District,2.0,80.0,NaN,80.0,6.0,...,1.0,"Internet, Refrigerator, TV, Air Conditioning, ...","Hospital, Clinic, Playground, Kindergarten, Bu...",0,7865000.0,UZS,30/04/2026,Описание Сдается в аренду 2/6/13 Юнусабад 13 к...,2026-05-02,https://www.olx.uz/d/obyavlenie/sdaetsya-v-are...
2,4lvjL,business,new building,Tashkent Region,Yunusabad District,3.0,NaN,NaN,80.0,6.0,...,0.0,"Internet, Refrigerator, TV, Air Conditioning, ...","Hospital, Clinic, School, Playground, Kinderga...",0,220000.0,USD,29/04/2026,Описание Продается квартира !!! 3/6/9 80 кВ По...,2026-05-02,https://www.olx.uz/d/obyavlenie/srochno-prodae...
3,4aiOy,private,NaN,Tashkent Region,Shaykhantakhur District,3.0,67.5,NaN,67.5,5.0,...,0.0,"Internet, Refrigerator, TV, Air Conditioning, ...",NaN,0,1400.0,USD,02/05/2026,"Описание Квартира в новостройке Tashkent City,...",2026-05-02,https://www.olx.uz/d/obyavlenie/sdaetsya-v-are...
4,4mAGS,business,resale,Tashkent Region,Yashnabad District,3.0,50.0,NaN,78.0,1.0,...,1.0,"Internet, Telephone, Refrigerator, TV, Air Con...","Hospital, Clinic, Playground, Kindergarten, Bu...",0,120000.0,USD,02/05/2026,Описание Продается своя квартира 3/1/4 Кирпичн...,2026-05-02,https://www.olx.uz/d/obyavlenie/kvartira-3-1-4...

## A. Malumotna uchun shartnoma

# Ma'lumotlar lug'ati — OLX.uz kvartiralar dataseti
 
> **Hajmi:** 18 000+ qator × 28 ustun  
> **Manba:** OLX.uz — kvartiralar bo'limi (`/nedvizhimost/kvartiry/`)  
> **Skraping sanasi:** 2026-04-15 - hozir

## B. Ma'lumotlarni qabul qilish va dastlabki tekshiruvlar

### B.1. Asosiy qabul qilish ro'yxati:

In [5]:
print(f'File nomi: olx_apartments.csv')
print(f'Qatorlar soni: {df.shape[0]}')
print(f'Ustunlar soni: {df.shape[1]}')
print(f"Ustun nomlari malumot ustuniga o'xshashmimi: (Ha/yoq): Ha")

File nomi: olx_apartments.csv
Qatorlar soni: 27077
Ustunlar soni: 28
Ustun nomlari malumot ustuniga o'xshashmimi: (Ha/yoq): Ha

### B.2. Noyoblik + dublikatlar (Dunyo talabi)

In [6]:
before = len(df)
after = df.duplicated().sum()
print(f"Dublikatlar soni: {after}")
print(f'Noyoblik soni: {before-after}')
df_cleaned = df.drop_duplicates()

Dublikatlar soni: 2409
Noyoblik soni: 24668

### B.3. Natija yaxlitligini tekshirish
  
>Faqatgina ko'zlangan malumonni o'z ichaga oladimi? (yani narxni)  
* 2 hil turdaki valyuta aralashgan UZB va USD.
>Biror yoqolgan qiymatlar bormi?
* Bor 50 rotiq
>G‘alati yozilgan (imlosi noto‘g‘ri) so‘zlar bormi?
* Hozircha kuzatilmadi

## C. Malumot sifati (Nima hato ekanligini isbotlash)
  
### C.1. Yetishmayotgan Qiymatlar Profili
 
**Dataset hajmi:** 18,267 qator (`price` ustunidagi 40 ta bo'sh qiymat o'chirilgandan keyin)
 
---
 
## Yetishmayotgan Qiymatlar Jadvali
 
| Ustun | Yetishmaydi (n) | % | Qabul qilinadimi? | Nega yetishmayotgan bo'lishi mumkin? |
|---|---|---|---|---|
| listing_id | 0 | 0.0% | ✅ Ha | — |
| seller_type | 1 | 0.0% | ✅ Ha | Kichik ma'lumot kiritish xatosi |
| housing_type | 5,956 | 32.6% | ⚠️ Balki | Forma to'ldirishda majburiy emas |
| region | 1 | 0.0% | ✅ Ha | Kichik ma'lumot kiritish xatosi |
| district | 1 | 0.0% | ✅ Ha | Kichik ma'lumot kiritish xatosi |
| rooms | 1 | 0.0% | ✅ Ha | Kichik ma'lumot kiritish xatosi |
| living_area_m2 | 12,862 | 70.4% | ❌ Yo'q | Sotuvchilar ko'pincha maydon ma'lumotini qoldirmaydi |
| kitchen_area_m2 | 14,775 | 80.9% | ❌ Yo'q | Alohida ko'rsatilmaydi; ixtiyoriy maydon |
| total_area_m2 | 4 | 0.0% | ✅ Ha | Deyarli to'liq |
| floor | 2 | 0.0% | ✅ Ha | Deyarli to'liq |
| total_floors | 1 | 0.0% | ✅ Ha | Deyarli to'liq |
| building_type | 4,488 | 24.6% | ⚠️ Balki | Sotuvchi har doim bilmasligi mumkin |
| layout | 6,378 | 34.9% | ⚠️ Balki | Ixtiyoriy maydon; subyektiv tasnif |
| build_year | 13,785 | 75.5% | ❌ Yo'q | Eski binolarda hujjat yo'q bo'lishi mumkin |
| ceiling_height | 12,486 | 68.4% | ❌ Yo'q | E'lonlarda kamdan-kam ko'rsatiladi |
| bathroom | 5,057 | 27.7% | ⚠️ Balki | Ko'p formatlarda ixtiyoriy |
| furnished | 3 | 0.0% | ✅ Ha | Deyarli to'liq |
| renovation | 3,370 | 18.4% | ⚠️ Balki | Sotuvchi ta'mirlash holatini ko'rsatmasligi mumkin |
| commission | 1 | 0.0% | ✅ Ha | Deyarli to'liq |
| amenities | 7,045 | 38.6% | ⚠️ Balki | Ixtiyoriy maydon; har doim to'ldirilmaydi |
| nearby | 6,523 | 35.7% | ⚠️ Balki | Ixtiyoriy qo'shimcha maydon |
| negotiable | 0 | 0.0% | ✅ Ha | — |
| price | 40 | 0.2% | ❌ Yo'q | Maqsad ustun — to'liq bo'lishi shart; o'chirildi |
| currency | 0 | 0.0% | ✅ Ha | — |
| published_date | 1 | 0.0% | ✅ Ha | Kichik ma'lumot kiritish xatosi |
| description | 1 | 0.0% | ✅ Ha | Deyarli to'liq |
| date_scraped | 0 | 0.0% | ✅ Ha | — |
| url | 0 | 0.0% | ✅ Ha | — |
 
---
 
## Yetishmayotgan Qiymatlar Tahlili
 
### Yetishmayotgan qiymatlar tasodifiy yoki tizimliymi?
 
Bu datasetdagi yetishmayotgan qiymatlar **to'liq tasodifiy emas**. `living_area_m2` (70.4%), `kitchen_area_m2` (80.9%), `build_year` (75.5%) va `ceiling_height` (68.4%) ustunlarida qiymatlarning aksariyati yo'q. Bu **tizimli muammo**ni ko'rsatadi: ushbu maydonlar platforma formasida ixtiyoriy bo'lgan yoki sotuvchilar ularni to'ldirishni istamagan.
 
### Yetishmayotgan qiymatlar narx (price) bilan bog'liqmi?
 
Jismoniy xususiyatlari (maydon, qurilish yili, shift balandligi) ko'rsatilmagan e'lonlar **past sifatli yoki norasmiy** bo'lishi mumkin, bu esa narxlarning ham past bo'lishiga olib keladi. Agar shunday bo'lsa, bu ustunlarni o'rtacha qiymat bilan to'ldirish (imputation) **narx bashoratlarini yuqori tomonga siljitishi** mumkin.
 
### Guruhlar bo'yicha yetishmayotgan % ni tekshirish (tavsiya)
 
```python
# housing_type bo'yicha yetishmayotgan %
df.groupby('housing_type').apply(lambda x: x.isnull().mean() * 100)
 
# region bo'yicha yetishmayotgan %
df.groupby('region').apply(lambda x: x.isnull().mean() * 100)
```
 
### Xulosa
 
Yetishmayotgan qiymatlar **qisman tizimli** xarakterga ega: `living_area_m2`, `kitchen_area_m2`, `build_year` va `ceiling_height` ustunlarida 68–81% qiymat yo'q, chunki platforma ularni ixtiyoriy maydon sifatida ko'rsatadi. Bu oddiy xato emas — bu sotuvchilarning e'lon to'ldirishdagi tarkibiy kamchiligidir. Modellashtirish oldidan ushbu ustunlar uchun qaror qabul qilish kerak: **ustunlarni o'chirish**, **ehtiyotkorlik bilan to'ldirish (imputation)**, yoki **yetishmayotganlikni alohida belgi (binary flag) sifatida saqlash**.

### Amal qiladigan oralag'i columnlar uchun
  
---
 
| Ustun | Ma'nosi | Turi | Mumkin qiymatlar / diapazon | O'lchov birligi | Izohlar |
| --- | --- | --- | --- | --- | --- |
| `listing_id` | E'lon unikal identifikatori | string | `'4jYx9'` kabi 5 belgili alfanumerik kod | — | OLX tomonidan avtomatik beriladi; asosiy kalit (primary key) sifatida ishlatiladi |
| `seller_type` | Sotuvchi turi | kategoriya | `private`, `business` | — | `private` — uy egasi o'zi; `business` — agentlik yoki firma |
| `housing_type` | Uy-joy turi | kategoriya | `resale`, `new building` | — | 2 834 ta qiymat yo'q; ko'pchilik `resale` |
| `region` | Viloyat | kategoriya | `Tashkent Region` va boshqa viloyatlar | — | Hozirgi ma'lumotlarda asosan Toshkent viloyati |
| `district` | Tuman / mahalla | kategoriya | `Chilanzar District`, `Yunusabad District` va boshqalar | — | Narx prognozi uchun eng muhim ustunlardan biri |
| `rooms` | Xonalar soni | raqam | `1` — `6+` | dona | Butun son kutiladi; modelda kategoriya sifatida ham ishlatish mumkin |
| `living_area_m2` | Yashash maydoni | raqam | taxminan `10` — `200` | m² | 5 777 ta qiymat yo'q (66%); mediana bilan to'ldirish + `missing` flagi tavsiya etiladi |
| `kitchen_area_m2` | Oshxona maydoni | raqam | taxminan `4` — `30` | m² | 6 656 ta qiymat yo'q (76%); yuqori yo'qotish darajasi |
| `total_area_m2` | Umumiy maydon | raqam | taxminan `15` — `500` | m² | Faqat 1 ta qiymat yo'q; narx prognozi uchun asosiy ustun |
| `floor` | Qavat | raqam | `1` — `30+` | qavat | 1 ta qiymat yo'q; mediana bilan to'ldirish yetarli |
| `total_floors` | Binodagi jami qavatlar soni | raqam | `2` — `30+` | qavat | Qiymat yo'q emas; `floor / total_floors` nisbati yaratish tavsiya etiladi |
| `building_type` | Bino turi | kategoriya | `panel`, `brick`, `monolith` | — | 2 029 ta qiymat yo'q; eng ko'p uchraydigan qiymat bilan to'ldirish |
| `layout` | Xonalar tartibi | kategoriya | `adjacent`, `separate`, `Смежно-раздельная` | — | Aralash til (rus/ingliz) bor — tozalash kerak; 2 840 ta qiymat yo'q |
| `build_year` | Qurilgan yil | raqam | `1950` — `2026` | yil | 6 197 ta qiymat yo'q; `building_age = 2026 - build_year` ustuni hosil qilish tavsiya etiladi |
| `ceiling_height` | Shift balandligi | raqam | `2.5` — `4.0` | metr | 5 683 ta qiymat yo'q; mediana bilan to'ldirish |
| `bathroom` | Hammom turi | kategoriya | `separate`, `combined` | — | 2 312 ta qiymat yo'q; eng ko'p uchraydigan qiymat bilan to'ldirish |
| `furnished` | Mebel mavjudligi | ikkilik (binary) | `1` — mebel bor, `0` — yo'q | — | Faqat 2 ta qiymat yo'q |
| `renovation` | Ta'mirlash holati | kategoriya | `euro renovation`, `average condition`, `designer renovation` | — | 1 538 ta qiymat yo'q; narxga sezilarli ta'sir ko'rsatadi |
| `commission` | Vositachi komissiyasi | ikkilik (binary) | `0` — yo'q, `1` — bor | — | Qiymat yo'q emas; `1` bo'lsa agentlik orqali sotiladi |
| `amenities` | Jihozlar ro'yxati | vergul bilan ajratilgan string | `Internet`, `TV`, `Air Conditioning`, `Balcony`, `Washing Machine` va boshqalar | — | 3 187 ta qiymat yo'q = jihozlar ko'rsatilmagan; multi-hot encoding tavsiya etiladi |
| `nearby` | Yaqin atrofdagi ob'ektlar | vergul bilan ajratilgan string | `School`, `Bus Stop`, `Park`, `Hospital`, `Supermarket` va boshqalar | — | 2 874 ta qiymat yo'q; multi-hot encoding tavsiya etiladi |
| `negotiable` | Narx kelishiladi | ikkilik (binary) | `1` — ha, `0` — yo'q | — | Qiymat yo'q emas |
| `price` | Narx | raqam | `500` — `2 000 000` (USDga o'tkazilgandan keyin) | USD yoki UZS | 13 ta qiymat yo'q — bu qatorlarni o'chirish kerak; avval valyutani normallashtirish shart |
| `currency` | Valyuta | kategoriya | `USD`, `UZS` | — | Modelga kirishdan oldin hammasi USDga aylantiriladi (1 USD ≈ 12 700 UZS) |
| `published_date` | E'lon joylashtirilgan sana | sana | `DD/MM/YYYY` formatida | sana | Modelda `days_since_posted` ustuniga aylantirish mumkin |
| `description` | E'lon matni | erkin matn | Rus va o'zbek tillarida | — | Modelga kiritilmaydi; NLP tahlili uchun alohida ishlatish mumkin |
| `date_scraped` | Skraping sanasi | sana | `YYYY-MM-DD` formatida | sana | Barcha qatorlarda `2026-05-02`; modelda ishlatilmaydi |
| `url` | E'lon havolasi | string | `https://www.olx.uz/d/obyavlenie/...` | — | Modelda ishlatilmaydi; manba sifatida saqlab qo'yish tavsiya etiladi |
 
---
 
## Tozalash bo'yicha qisqacha yo'riqnoma
 
| Muammo | Ta'sirlangan ustunlar | Yechim |
| --- | --- | --- |
| Maqsadli qiymat yo'q | `price` (13 ta) | Qatorlarni o'chirish |
| Yuqori yo'qotish (>50%) | `living_area_m2`, `kitchen_area_m2`, `build_year`, `ceiling_height` | Mediana bilan to'ldirish + `_missing` flagi |
| O'rtacha yo'qotish | `housing_type`, `building_type`, `layout`, `bathroom`, `renovation` | Eng ko'p uchraydigan qiymat (mode) bilan to'ldirish |
| Aralash valyuta | `price`, `currency` | Hammasi USDga o'tkazish |
| Aralash til | `layout` | `Смежно-раздельная` → `mixed` deb standartlashtirish |
| Vergul bilan ajratilgan qiymatlar | `amenities`, `nearby` | Multi-hot encoding (har bir teg — alohida ustun) |

## D. Tozalash strategiyasi (nafaqat qadamlar-qarorlar)
  
### D.1 Standartlashtirish qoidalari (kategoriyaviy)
`seller_type` --> Faqatgina 2 dona categoria aniqlandi. Ortiqcha tekshiruv talab qilmaydi.  
`housing_type` --> 6 ga yaqin categoria aniqladi. Uchta rus tilodagi miqdorlar("новостройка", "Новостройка", "Новостройка.") --> new building  
`region` -- > Hammasi joyida.

In [14]:
df_cleaned['district'].value_counts()

district
Mirzo-Ulugbek District    4020
Yunusabad District        3007
Yakkasaray District       2683
Yashnabad District        2395
Mirabad District          2329
                          ...
Чуст                         1
Тамдыбулак                   1
Ходжейли                     1
Яккабаг                      1
Акташ                        1
Name: count, Length: 130, dtype: int64

---

In [8]:
df_cleaned[df_cleaned['price'].isnull()]

,listing_id,seller_type,housing_type,region,district,rooms,living_area_m2,kitchen_area_m2,total_area_m2,floor,...,commission,amenities,nearby,negotiable,price,currency,published_date,description,date_scraped,url
1314,4mwtN,private,NaN,Tashkent Region,Бектемирский район,3.0,45.0,12.0,66.0,6.0,...,0.0,"Internet, Refrigerator, TV, Cable TV, Washing ...","Hospital, Clinic, Playground, Kindergarten, Bu...",0,NaN,USD,29/04/2026,Описание Musaffo maskan 3/6/10 400$ ichida ha...,2026-05-02,https://www.olx.uz/d/obyavlenie/musaffo-maskan...
2126,4ms7L,business,NaN,Tashkent Region,Mirzo-Ulugbek District,2.0,56.0,NaN,56.0,14.0,...,1.0,NaN,NaN,1,NaN,USD,01/05/2026,Описание Мирзо-Улугбекский район ЖК Akay City ...,2026-05-02,https://www.olx.uz/d/obyavlenie/akay-city-2-ko...
3926,4mCMT,business,new building,Tashkent Region,Yashnabad District,2.0,NaN,NaN,60.0,6.0,...,1.0,NaN,NaN,0,NaN,USD,02/05/2026,Описание Срочно Продаётся Новостройка 2 комнат...,2026-05-02,https://www.olx.uz/d/obyavlenie/srochno-novost...
4431,4mCEI,business,NaN,Tashkent Region,Yashnabad District,2.0,NaN,NaN,52.0,6.0,...,1.0,"Internet, Telephone, Refrigerator, TV, Air Con...","Hospital, Clinic, Playground, Kindergarten, Bu...",1,NaN,USD,02/05/2026,Описание Район: Яшнабод Ориентир: Better best ...,2026-05-02,https://www.olx.uz/d/obyavlenie/arenda-kvartir...
4624,4lDkg,business,NaN,Обмен - Ферганская область,Обмен - Маргилан,3.0,56.0,15.0,56.0,2.0,...,0.0,"Telephone, Cable TV, TV, Internet","Entertainment, Bus Stop, School, Supermarket, ...",0,NaN,USD,02/05/2026,Описание Ijaraga beriladi yoki hovli uyga bart...,2026-05-02,https://www.olx.uz/d/obyavlenie/dom-ijaraga-be...
4768,4bJO4,business,NaN,Tashkent Region,Yashnabad District,2.0,NaN,NaN,54.0,12.0,...,1.0,NaN,NaN,0,NaN,USD,02/05/2026,Описание Сдаётся 2х комнатнаям квартира на Яшн...,2026-05-02,https://www.olx.uz/d/obyavlenie/yashnabad-zhk-...
4778,41xEz,business,NaN,Tashkent Region,Алмазарский район,2.0,NaN,NaN,50.0,3.0,...,1.0,NaN,NaN,0,NaN,USD,02/05/2026,"Описание ЖК ""Алмазар сити"" 2х комнатная евро ...",2026-05-02,https://www.olx.uz/d/obyavlenie/almazar-siti-2...
4784,3Ka9o,business,NaN,Tashkent Region,Алмазарский район,1.0,32.0,NaN,32.0,3.0,...,0.0,NaN,NaN,0,NaN,USD,02/05/2026,"Описание Северный Алмазар, Жомий Алмазар сити ...",2026-05-02,https://www.olx.uz/d/obyavlenie/severnyy-olmaz...
4847,3voF3,private,NaN,Обмен - Ташкент,Обмен - Сергелийский район,2.0,25.0,7.0,60.0,5.0,...,0.0,NaN,NaN,0,NaN,USD,02/05/2026,"Описание 2³ комнатная 60 м2, продам или обмен....",2026-05-02,https://www.olx.uz/d/obyavlenie/2-komnatnaya-6...
7570,4lUeo,business,NaN,Tashkent Region,Chilanzar District,3.0,NaN,NaN,70.0,3.0,...,1.0,"Cable TV, TV, Telephone, Balcony, Washing Mach...","Entertainment, Bus Stop, School, Supermarket, ...",1,NaN,USD,02/05/2026,Описание Аренда квартира: #Чиланзарский рай...,2026-05-02,https://www.olx.uz/d/obyavlenie/arenda-kvartir...
7626,4lUdg,business,NaN,Tashkent Region,Uchtepa District,2.0,NaN,NaN,60.0,16.0,...,1.0,"Cable TV, TV, Telephone, Balcony, Washing Mach...","Entertainment, Bus Stop, School, Supermarket, ...",1,NaN,USD,02/05/2026,Описание #Урикзор битонка #Навастройка #Аренда...,2026-05-02,https://www.olx.uz/d/obyavlenie/arenda-kvartir...
7791,4lUZo,business,new building,Tashkent Region,Yakkasaray District,1.0,20.0,5.0,25.0,8.0,...,0.0,"Kitchen, TV, Balcony, Air Conditioning, Intern...","Restaurant, Cafe, Kindergarten, Parking, Bus S...",1,NaN,USD,01/05/2026,Описание Яккасарой шота руставелида. Жк. ...,2026-05-02,https://www.olx.uz/d/obyavlenie/yakkasaray-zhk...
8408,46Kc2,private,NaN,Tashkent Region,Chilanzar District,2.0,55.0,15.0,60.0,1.0,...,1.0,"Air Conditioning, Refrigerator, Washing Machin...",NaN,0,NaN,USD,02/05/2026,Описание Chilonzor 17-kvartalda -1 ETAJDA SOKO...,2026-05-02,https://www.olx.uz/d/obyavlenie/arenda-chilonz...
9248,4mivj,private,NaN,Tashkent Region,Sergeli District,2.0,50.0,9.0,60.0,3.0,...,1.0,"Internet, Telephone, Refrigerator, TV, Air Con...","Hospital, Clinic, Playground, Kindergarten, Bu...",0,NaN,USD,03/05/2026,Описание Ижара 2 хонали спутник 16 3-этаж Хамм...,2026-05-03,https://www.olx.uz/d/obyavlenie/arenda-sergeli...
9329,4mELi,business,NaN,Tashkent Region,Эшангузар,2.0,55.0,55.0,55.0,3.0,...,1.0,"Internet, Refrigerator, TV, Air Conditioning, ...","Hospital, Clinic, Playground, Kindergarten, Bu...",0,NaN,USD,03/05/2026,Описание *Сдаётся аренда квартира в эшонгузар ...,2026-05-03,https://www.olx.uz/d/obyavlenie/arenda-eshongu...
9644,4mCSM,private,new building,Tashkent Region,Chilanzar District,3.0,82.0,10.0,83.0,1.0,...,0.0,"Balcony, Air Conditioning, Cable TV, Internet,...","Restaurant, Cafe, Kindergarten, Parking, Bus S...",1,NaN,USD,03/05/2026,Описание Продаю свою кВ 3комнатную Адрес: Якка...,2026-05-03,https://www.olx.uz/d/obyavlenie/prodayu-svoyu-...
10076,3zezU,business,new building,Tashkent Region,Yashnabad District,3.0,55.0,12.0,72.0,9.0,...,0.0,NaN,NaN,0,NaN,USD,03/05/2026,Описание Yashnabod tumanida 3 xona uy sotiladi...,2026-05-03,https://www.olx.uz/d/obyavlenie/yashnabod-tuma...
10085,3RZY9,business,new building,Tashkent Region,Sergeli District,3.0,42.0,12.0,58.0,7.0,...,0.0,"Balcony, Cable TV, Kitchen, Internet",NaN,0,NaN,USD,03/05/2026,Описание Янги ҳаёт тумани 5а да 3 хона сотилад...,2026-05-03,https://www.olx.uz/d/obyavlenie/yangi-aet-tuma...
10100,3GkoN,business,new building,Tashkent Region,Sergeli District,2.0,35.0,12.0,56.0,3.0,...,0.0,"Balcony, Cable TV, Kitchen, Internet",NaN,0,NaN,USD,03/05/2026,Описание Янги хаёт тумани 8- худудда 3 қаватда...,2026-05-03,https://www.olx.uz/d/obyavlenie/yangi-haet-tum...
10652,3ILKM,private,NaN,Обмен - Ташкентская область,Обмен - Чирчик,3.0,37.0,NaN,67.0,4.0,...,0.0,"Balcony, Air Conditioning","School, Supermarket, Shops, Park, Green Area, ...",0,NaN,USD,03/05/2026,Описание 3× комнатная квартиру меняю на ваш до...,2026-05-03,https://www.olx.uz/d/obyavlenie/3-komnatnaya-k...
10868,4jU0N,business,resale,Tashkent Region,Mirabad District,3.0,NaN,NaN,84.0,3.0,...,0.0,NaN,NaN,0,NaN,USD,03/05/2026,Описание Нукусская улучшенка 3/3/9 84 КВ 148000$,2026-05-03,https://www.olx.uz/d/obyavlenie/nukusskaya-3-3...
12307,4lVQe,business,resale,Tashkent Region,Mirabad District,1.0,28.0,3.0,35.0,1.0,...,1.0,NaN,"Hospital, Clinic, Playground, Kindergarten, Bu...",0,NaN,USD,03/05/2026,Описание Квартира сотилади! Манзил: Миробод ту...,2026-05-03,https://www.olx.uz/d/obyavlenie/kvartira-sotil...
12684,4lX6a,business,resale,Tashkent Region,Yunusabad District,2.0,NaN,NaN,60.0,1.0,...,0.0,NaN,NaN,1,NaN,USD,03/05/2026,Описание Юнусабад 10 2/1/5 60м2 Улучшенная пла...,2026-05-03,https://www.olx.uz/d/obyavlenie/kvartira-yunus...
12727,4lX4C,business,resale,Tashkent Region,Yunusabad District,2.0,NaN,NaN,50.0,1.0,...,0.0,NaN,NaN,0,NaN,USD,03/05/2026,Описание Юнусабад 11 2/1/4 50м2 Балкон 1.5*6 Т...,2026-05-03,https://www.olx.uz/d/obyavlenie/kvartira-yunus...
12803,4lX2Q,business,resale,Tashkent Region,Yunusabad District,2.0,NaN,NaN,60.0,1.0,...,0.0,NaN,NaN,0,NaN,USD,03/05/2026,Описание Юнусабад 10 2/1/5 60м2 Балкон 2*6 Сос...,2026-05-03,https://www.olx.uz/d/obyavlenie/kvartira-yunus...
13242,4mkQk,business,resale,Tashkent Region,Yashnabad District,3.0,NaN,NaN,68.0,4.0,...,0.0,NaN,NaN,0,NaN,USD,03/05/2026,Описание Район: Яшнабод Кўча: Асалобод Мўлжал:...,2026-05-03,https://www.olx.uz/d/obyavlenie/srochno-svoya-...
13526,4lXg8,business,resale,Tashkent Region,Yunusabad District,2.0,NaN,NaN,61.0,5.0,...,0.0,NaN,NaN,1,NaN,USD,03/05/2026,Описание Юунусабад 14-квартал Ориентир: Сайрам...,2026-05-03,https://www.olx.uz/d/obyavlenie/kvartira-yunus...
13661,4lXcp,business,resale,Tashkent Region,Yunusabad District,1.0,NaN,NaN,45.0,3.0,...,0.0,NaN,NaN,0,NaN,USD,03/05/2026,Описание Юнусабад 10 1/3/5 45м2 Улучшения план...,2026-05-03,https://www.olx.uz/d/obyavlenie/kvartira-yunus...
14153,4mH43,private,NaN,Обмен - Ташкент,Обмен - Мирзо-Улугбекский район,3.0,NaN,17.0,82.0,5.0,...,1.0,"Internet, Refrigerator, Washing Machine, Kitchen","Hospital, Clinic, Playground, Kindergarten, Bu...",0,NaN,USD,03/05/2026,Описание Меняю или продаю квартиру в Риге (Лат...,2026-05-03,https://www.olx.uz/d/obyavlenie/obmen-prodazha...
14204,4mkX4,business,resale,Tashkent Region,Yashnabad District,2.0,NaN,NaN,50.0,2.0,...,1.0,NaN,NaN,0,NaN,USD,03/05/2026,Описание СРОЧНО Продаётся 2 в3 - комнатная ква...,2026-05-03,https://www.olx.uz/d/obyavlenie/srochno-yashno...
14749,4mHaU,private,NaN,Samarkand Region,Samarkand,2.0,50.0,10.0,50.0,7.0,...,0.0,"Refrigerator, TV, Washing Machine, Kitchen",NaN,1,NaN,USD,03/05/2026,Описание Kvartira ijaraga beramiz Briliant Cit...,2026-05-03,https://www.olx.uz/d/obyavlenie/arenda-kvartir...
15780,2Rnay,private,NaN,Обмен - Хорезмская область,Обмен - Ургенч,3.0,60.0,10.0,60.0,2.0,...,0.0,"Telephone, Kitchen, Internet, Cable TV, TV, Re...","School, Supermarket, Shops, Park, Green Area, ...",0,NaN,USD,04/05/2026,Описание Урганч шахар Марказидаги барча қулайл...,2026-05-04,https://www.olx.uz/d/obyavlenie/toshkent-shahr...
15867,4mI6G,private,NaN,Tashkent Region,Chilanzar District,2.0,52.0,20.0,52.0,3.0,...,1.0,NaN,NaN,0,NaN,USD,04/05/2026,Описание Чилонзор Ок Тепа Круг Евро Ремонт 2/3...,2026-05-04,https://www.olx.uz/d/obyavlenie/chilonzor-ok-t...
16542,4iIvx,private,NaN,Обмен - Навоийская область,Обмен - Навои,3.0,72.3,16.0,72.3,1.0,...,0.0,"Internet, Cable TV, Kitchen","School, Playground, Bus Stop, Park, Green Area...",0,NaN,USD,04/05/2026,Описание Алмаштираман келишган холда 3 хона 1 ...,2026-05-04,https://www.olx.uz/d/obyavlenie/obmen-eki-soti...
16560,3SPJp,private,NaN,Tashkent Region,Sergeli District,1.0,18.0,13.0,100.0,1.0,...,0.0,"Internet, Refrigerator, TV, Washing Machine, K...","Hospital, Clinic, School, Playground, Kinderga...",0,NaN,USD,04/05/2026,Описание Eski sergelida uchaska 4 ta xona hamm...,2026-05-04,https://www.olx.uz/d/obyavlenie/eski-sergeli-u...
17431,4mIxG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0,NaN,USD,NaN,NaN,2026-05-04,https://www.olx.uz/d/obyavlenie/ahmad-yugnakiy...
17551,4lCfv,business,NaN,Tashkent Region,Chilanzar District,3.0,50.0,NaN,50.0,3.0,...,0.0,NaN,NaN,1,NaN,USD,04/05/2026,Описание Аренда квартира: #Чилонзор район #Ори...,2026-05-04,https://www.olx.uz/d/obyavlenie/arenda-novza-m...
17576,4hG27,private,resale,Tashkent Region,Yashnabad District,3.0,68.0,4.0,70.0,4.0,...,0.0,"Kitchen, Balcony","Hospital, Clinic, Playground, Kindergarten, Bu...",1,NaN,USD,04/05/2026,Описание Uy sotiladi srochna olmos maxala 16 e...,2026-05-04,https://www.olx.uz/d/obyavlenie/uy-sotiladi-ol...
20188,4mKf5,private,NaN,Tashkent Region,Sergeli District,2.0,52.0,20.0,68.0,3.0,...,0.0,"Internet, Telephone, Refrigerator, TV, Air Con...","Hospital, Clinic, Playground, Kindergarten, Bu...",0,NaN,USD,04/05/2026,Описание 2- комнатная квартира без посреднико...,2026-05-04,https://www.olx.uz/d/obyavlenie/kvartira-bez-p...
20459,3HigA,private,resale,Tashkent Region,Yashnabad District,5.0,109.0,NaN,109.0,5.0,...,1.0,NaN,NaN,0,NaN,USD,04/05/2026,Описание Г.Ташкент яшнабадский район (40 лет п...,2026-05-04,https://www.olx.uz/d/obyavlenie/srochno-prodae...
22004,4lEgh,business,NaN,Tashkent Region,Sergeli District,1.0,10.0,8.0,30.0,1.0,...,1.0,"Telephone, Refrigerator, TV, Air Conditioning,...","Hospital, Clinic, School, Playground, Kinderga...",0,NaN,USD,04/05/2026,Описание Янги хаёт спутник 9 1-хонали 1-этаж Ш...,2026-05-04,https://www.olx.uz/d/obyavlenie/arenda-sergeli...
22731,4m8l1,business,new building,Tashkent Region,Uchtepa District,2.0,59.0,16.0,59.0,16.0,...,1.0,"Internet, Telephone, Air Conditioning, Cable T...","Hospital, Clinic, Playground, Kindergarten, Bu...",0,NaN,USD,04/05/2026,Описание Тошкент Шахар Учтепа район 2 хона 16 ...,2026-05-05,https://www.olx.uz/d/obyavlenie/urizor-reziden...
23509,4moEE,business,resale,Tashkent Region,Yashnabad District,1.0,NaN,NaN,38.0,1.0,...,0.0,NaN,NaN,0,NaN,USD,04/05/2026,Описание ПРОДAЖA - Квартира #Вторичка ID: 1789...,2026-05-05,https://www.olx.uz/d/obyavlenie/srochno-svoya-...
23873,4mMUH,private,NaN,Tashkent Region,Yakkasaray District,3.0,NaN,NaN,100.0,3.0,...,0.0,NaN,NaN,0,NaN,USD,05/05/2026,Описание Kvartirada xamma narsa bor. Bir kishi...,2026-05-05,https://www.olx.uz/d/obyavlenie/kvartiraga-bit...
24873,4mHaU,private,NaN,Samarkand Region,Samarkand,2.0,50.0,10.0,50.0,7.0,...,0.0,"Refrigerator, TV, Washing Machine, Kitchen",NaN,1,NaN,USD,04/05/2026,Описание Kvartira ijaraga beramiz Briliant Cit...,2026-05-05,https://www.olx.uz/d/obyavlenie/arenda-kvartir...
25424,4mNJJ,business,NaN,Tashkent Region,Алмазарский район,2.0,NaN,NaN,52.0,9.0,...,1.0,NaN,NaN,0,NaN,USD,05/05/2026,"Описание 2 хонали квартира ЖК "" Олмазор сити"" ...",2026-05-05,https://www.olx.uz/d/obyavlenie/zhk-olmazor-si...
25605,3PKt8,business,NaN,Tashkent Region,Алмазарский район,2.0,NaN,NaN,53.0,2.0,...,1.0,NaN,NaN,0,NaN,USD,05/05/2026,Описание Сдаётся 2х комнатная квартира на Алм...,2026-05-05,https://www.olx.uz/d/obyavlenie/almazar-siti-2...
25689,4hig7,business,new building,Tashkent Region,Алмазарский район,2.0,52.0,15.0,52.0,3.0,...,1.0,Balcony,"Hospital, Clinic, School, Playground, Kinderga...",1,NaN,USD,05/05/2026,Описание Продаётся квартира в Алмазарском райо...,2026-05-05,https://www.olx.uz/d/obyavlenie/qora-qamish-na...
25696,3Xsks,business,NaN,Tashkent Region,Алмазарский район,2.0,NaN,NaN,50.0,8.0,...,1.0,"Refrigerator, TV, Air Conditioning, Washing Ma...",NaN,0,NaN,USD,05/05/2026,"Описание ЖК "" Olmazor City"" 2хона 50м2 Болалар...",2026-05-05,https://www.olx.uz/d/obyavlenie/almazar-siti-2...
26170,4mt8C,business,resale,Tashkent Region,Yunusabad District,1.0,NaN,NaN,18.0,3.0,...,0.0,NaN,NaN,1,NaN,USD,06/05/2026,Описание Бадамзар Бывшее общежитие 1/3/4 Общая...,2026-05-06,https://www.olx.uz/d/obyavlenie/kvartira-bodom...

In [9]:
df_cleaned[df_cleaned['currency'] == "UZS"]

,listing_id,seller_type,housing_type,region,district,rooms,living_area_m2,kitchen_area_m2,total_area_m2,floor,...,commission,amenities,nearby,negotiable,price,currency,published_date,description,date_scraped,url
1,4myoT,private,NaN,Tashkent Region,Yunusabad District,2.0,80.0,NaN,80.0,6.0,...,1.0,"Internet, Refrigerator, TV, Air Conditioning, ...","Hospital, Clinic, Playground, Kindergarten, Bu...",0,7865000.0,UZS,30/04/2026,Описание Сдается в аренду 2/6/13 Юнусабад 13 к...,2026-05-02,https://www.olx.uz/d/obyavlenie/sdaetsya-v-are...
24,49bVu,private,NaN,Samarkand Region,Лаиш,2.0,65.0,NaN,10.0,1.0,...,1.0,"Internet, Telephone, Refrigerator, TV, Air Con...","Hospital, Clinic, School, Playground, Kinderga...",0,4000000.0,UZS,02/05/2026,Описание Samarqand shahar Qorasuv massiv 2 xon...,2026-05-02,https://www.olx.uz/d/obyavlenie/bez-agestvo-ij...
29,4lwkw,private,NaN,Khorezm Region,Ургенч,3.0,49.0,10.0,62.0,3.0,...,0.0,"Refrigerator, TV, Air Conditioning, Washing Ma...","Hospital, Clinic, School, Playground, Kinderga...",0,2800000.0,UZS,02/05/2026,Описание Ургенч шахар марказида мед институтга...,2026-05-02,https://www.olx.uz/d/obyavlenie/kvartira-izhar...
30,3nWuH,private,resale,Samarkand Region,Samarkand,5.0,86.0,12.0,100.0,4.0,...,0.0,"Kitchen, Balcony","Hospital, Clinic, Playground, Kindergarten, Bu...",0,900000000.0,UZS,02/05/2026,Описание 5 хона 6 хона килинган квартира сотил...,2026-05-02,https://www.olx.uz/d/obyavlenie/6-honalik-kvar...
33,3It0w,private,NaN,Tashkent Region,Yashnabad District,4.0,100.0,12.0,92.0,5.0,...,1.0,"Internet, Telephone, Refrigerator, TV, Air Con...","School, Playground, Kindergarten, Bus Stop, Pa...",1,1300000.0,UZS,02/05/2026,"Описание Квартирага боллани куяман, 1.300 000...",2026-05-02,https://www.olx.uz/d/obyavlenie/kvartiraga-ish...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26965,4282H,private,NaN,Fergana Region,Фергана,2.0,40.0,15.0,60.0,8.0,...,1.0,"Kitchen, Balcony","School, Kindergarten, Bus Stop, Park, Green Ar...",1,2000000.0,UZS,06/05/2026,Описание Аэропорт кўчаси йўлни бўйида 9 этажли...,2026-05-06,https://www.olx.uz/d/obyavlenie/aeroport-va-ta...
26997,432Mq,private,NaN,Kashkadarya Region,Карши,3.0,54.0,12.0,74.0,13.0,...,0.0,"Internet, Telephone, Refrigerator, TV, Air Con...","Hospital, Clinic, School, Playground, Kinderga...",0,2750000.0,UZS,04/05/2026,Описание 3 хона барча шароитга эга уй ижарага ...,2026-05-06,https://www.olx.uz/d/obyavlenie/sitidan-3-hona...
27001,4mPMl,business,NaN,Bukhara Region,Bukhara,3.0,NaN,NaN,82.0,4.0,...,1.0,NaN,NaN,0,1900000.0,UZS,06/05/2026,Описание Квартира 6 микрда жойлащган Хамма шар...,2026-05-06,https://www.olx.uz/d/obyavlenie/kvartira-izhar...
27032,4jciN,business,NaN,Samarkand Region,Samarkand,2.0,50.0,5.0,61.0,1.0,...,0.0,"Refrigerator, Kitchen, Balcony","Hospital, Clinic, Playground, Kindergarten, Bu...",1,2200000.0,UZS,06/05/2026,Описание Сдается 2 х комнатная квартира на БА...,2026-05-06,https://www.olx.uz/d/obyavlenie/sdaetsya-kvart...
27066,4mO5E,private,NaN,Tashkent Region,Yunusabad District,3.0,72.0,6.0,78.0,1.0,...,0.0,"Internet, Refrigerator, TV, Air Conditioning, ...","Playground, Kindergarten, Bus Stop, Park, Gree...",1,950000.0,UZS,05/05/2026,Описание Yunusobod tumanida Alfraganus univers...,2026-05-06,https://www.olx.uz/d/obyavlenie/yunusobod-alfr...

In [ ]:
# Birinchi bo'lib narxi yo'q qatorlarni olib tashlaymiz
before1 = len(df_cleaned['price'])
df_cleaned.dropna(subset=['price'], inplace=True)
print(f"Qatorlar soni(Dublikat bilan): {before1}")
print(f"Olib tashlangan qator soni: {before1 - len(df_cleaned['price'])}")
print(f"Noyoblik soni: {len(df_cleaned['price'])}")

# Endi bir xil valyutaga o'tqazib olamiz
exchange_rate = 12700
df_cleaned['price_usd'] = df_cleaned['price']
df_cleaned.loc[df_cleaned['currency']=="UZS", 'price_usd'] = (
    df_cleaned.loc[df_cleaned['currency']=="UZS", 'price_usd'] / exchange_rate
).round(1)

Qatorlar soni(Dublikat bilan): 24668
Olib tashlangan qator soni: 50
Noyoblik soni: 24618

/var/folders/pn/2q111n451j10mgh135bwncf00000gn/T/ipykernel_38121/3476733231.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned.dropna(subset=['price'], inplace=True)
/var/folders/pn/2q111n451j10mgh135bwncf00000gn/T/ipykernel_38121/3476733231.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['price_usd'] = df_cleaned['price']

In [11]:
df_cleaned.loc[df_cleaned['price_usd'] < 12000]

,listing_id,seller_type,housing_type,region,district,rooms,living_area_m2,kitchen_area_m2,total_area_m2,floor,...,amenities,nearby,negotiable,price,currency,published_date,description,date_scraped,url,price_usd
1,4myoT,private,NaN,Tashkent Region,Yunusabad District,2.0,80.0,NaN,80.0,6.0,...,"Internet, Refrigerator, TV, Air Conditioning, ...","Hospital, Clinic, Playground, Kindergarten, Bu...",0,7865000.0,UZS,30/04/2026,Описание Сдается в аренду 2/6/13 Юнусабад 13 к...,2026-05-02,https://www.olx.uz/d/obyavlenie/sdaetsya-v-are...,619.3
3,4aiOy,private,NaN,Tashkent Region,Shaykhantakhur District,3.0,67.5,NaN,67.5,5.0,...,"Internet, Refrigerator, TV, Air Conditioning, ...",NaN,0,1400.0,USD,02/05/2026,"Описание Квартира в новостройке Tashkent City,...",2026-05-02,https://www.olx.uz/d/obyavlenie/sdaetsya-v-are...,1400.0
15,4lUZf,private,NaN,Bukhara Region,Bukhara,3.0,87.0,20.0,100.0,1.0,...,"Internet, Telephone, Refrigerator, TV, Air Con...","Hospital, Clinic, Playground, Kindergarten, Bu...",0,350.0,USD,02/05/2026,Описание Квартира 3 хона 1 этаж. ремонт килинг...,2026-05-02,https://www.olx.uz/d/obyavlenie/3-honali-uy-1-...,350.0
20,4m2lH,business,NaN,Tashkent Region,Mirzo-Ulugbek District,5.0,100.0,NaN,240.0,1.0,...,"Internet, Telephone, Refrigerator, TV, Cable T...","Hospital, Clinic, Playground, Kindergarten, Bu...",0,800.0,USD,01/05/2026,Описание Convenient for foreigners. Quiet neig...,2026-05-02,https://www.olx.uz/d/obyavlenie/dolgosrochnaya...,800.0
21,4igVz,private,NaN,Samarkand Region,Samarkand,3.0,50.0,20.0,76.0,2.0,...,"Kitchen, TV, Balcony, Air Conditioning, Intern...","Restaurant, Cafe, Kindergarten, Parking, Bus S...",1,500.0,USD,30/04/2026,Описание Здается 2х комнатная квартира на 2м з...,2026-05-02,https://www.olx.uz/d/obyavlenie/sdaetsya-2h-ko...,500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27048,4m6wD,business,NaN,Tashkent Region,Yunusabad District,3.0,NaN,NaN,95.0,7.0,...,"Cable TV, TV, Telephone, Balcony, Washing Mach...","School, Bus Stop, Playground, Park, Green Area...",1,800.0,USD,06/05/2026,Описание АРЕНДА КВАРТИРЫ! Район:Юнусабадский р...,2026-05-06,https://www.olx.uz/d/obyavlenie/arenda-3-komna...,800.0
27053,3UnGc,private,NaN,Tashkent Region,Yashnabad District,2.0,NaN,NaN,54.0,4.0,...,"Air Conditioning, Washing Machine, Internet, K...","Kindergarten, Bus Stop, Hospital, Clinic, Rest...",1,450.0,USD,06/05/2026,Описание Сдается в аренду укомплектованная 2/4...,2026-05-06,https://www.olx.uz/d/obyavlenie/arenda-ttz-2-o...,450.0
27060,4m6wh,business,NaN,Tashkent Region,Mirzo-Ulugbek District,2.0,60.0,NaN,60.0,2.0,...,NaN,NaN,0,900.0,USD,06/05/2026,Описание Район: Мирзо-Улугбекский Ориентир: Ц-...,2026-05-06,https://www.olx.uz/d/obyavlenie/arenda-ts1-sda...,900.0
27066,4mO5E,private,NaN,Tashkent Region,Yunusabad District,3.0,72.0,6.0,78.0,1.0,...,"Internet, Refrigerator, TV, Air Conditioning, ...","Playground, Kindergarten, Bus Stop, Park, Gree...",1,950000.0,UZS,05/05/2026,Описание Yunusobod tumanida Alfraganus univers...,2026-05-06,https://www.olx.uz/d/obyavlenie/yunusobod-alfr...,74.8
27069,4m6w1,business,NaN,Tashkent Region,Mirzo-Ulugbek District,3.0,NaN,NaN,75.0,3.0,...,NaN,NaN,0,1000.0,USD,06/05/2026,Описание Сдаётся в Аренду квартира! Буюк Ипак ...,2026-05-06,https://www.olx.uz/d/obyavlenie/sdaetsya-v-are...,1000.0